<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestRail1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>706e5968-6ead-4f4e-a65c-fcfbd87f36eb</testSuiteGuid>
   <testCaseLink>
      <guid>e585d45d-326e-424d-8957-8c4df9159943</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestRail/GSM Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>68294cca-1602-430d-a8da-0697490bdff3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Offers Regression/GSM Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>68294cca-1602-430d-a8da-0697490bdff3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>b6b60e09-ad6f-4a0c-9491-83d2b86c5606</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>68294cca-1602-430d-a8da-0697490bdff3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>ca0041c3-4cb8-4d42-aafb-0c3e4f59a876</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>68294cca-1602-430d-a8da-0697490bdff3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e72bdbe1-029f-47b0-ae14-f4b446c9ac0f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
